server:
  port: 8080
  #设置请求与响应都使用自定义编码格式
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  data:
    #  #redis配置 redis在 data 下面
    redis:
      # Redis数据库索引（默认为0）
      database: 3
      #redis服务器地址
      #    host: 1.15.181.152
      host: 1.15.181.152
      #端口
      port: 6379
      #密码
      password: w.c.520.
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: GBK

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ay_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #是否开启驼峰映射
    map-underscore-to-camel-case: true
  # 搜索指定包别名
  type-aliases-package: com.ay.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  #  mapper-locations: classpath*:/mapper/**/*.xml

  # 全局配置id自增  =>
  global-config:
    db-config:
      id-type: auto


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false